import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/Sidebar'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="antialiased">
      <body className={`${inter.variable} antialiased`}>
        <div className="grid-cols-app grid min-h-screen">
          <Sidebar />
          <main className="px-8 pt-8 pb-12">{children}</main>
        </div>
      </body>
    </html>
  )
}
